base: 
  random_state: 42

data_process:
  in_path: 'data/raw/iris.csv'
  out_path: 'data/iris_engineered.csv'
  
data_split:
  test_size: 0.2
  train_set_path: 'data/processes/train_iris.csv'
  test_set_path: 'data/processes/test_iris.csv'

train:

  clf_params:
    C: 0.001
    solver: 'lbfgs'
    multi_class: 'multinomial'
    max_iter: 100
  
  cv: 3
  estimater_name: logreg
  model_path: 'models/model.joblib'

reports:
  confusion_matrix_png: 'reports/confusion_matrix.png'

